=== jaimeleite/PRI/TP2/pr.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT pr (informacaoGeral, trabalhosAEntregar, resumo, avaliandos) >

<!--Elemento informacaoGeral-->
<!ELEMENT informacaoGeral (dataInicio, dataFim, nomeCadeira,numTpc, professor, titulo, subTitulo?) >
<!ELEMENT dataInicio (#PCDATA) >
<!ELEMENT dataFim (#PCDATA) >
<!ELEMENT nomeCadeira (#PCDATA) >
<!ELEMENT numTpc (#PCDATA) >
<!ELEMENT professor (#PCDATA|ligacao)* >
          
<!ELEMENT titulo (#PCDATA) >
<!ELEMENT subTitulo (#PCDATA) >

<!--Elemento trabalhosAEntregar-->
<!ELEMENT trabalhosAEntregar (ligacao)+ >
<!ELEMENT ligacao (#PCDATA) >
<!ATTLIST ligacao
          pWeb CDATA #REQUIRED >
          
          
<!--Elemento resumo-->
<!ELEMENT resumo (p+) >
<!ELEMENT p (#PCDATA|ligacao|bold|italico|underline)* >

<!--Elemento avaliandos-->
<!ELEMENT avaliandos (aluno+) >
<!ELEMENT aluno (nome,curso,numeroAluno,email) >
<!ELEMENT nome (#PCDATA) >
<!ELEMENT curso (#PCDATA) >
<!ATTLIST curso
          pWeb CDATA #REQUIRED >
<!ELEMENT numeroAluno (#PCDATA) >
<!ELEMENT email (#PCDATA) >

<!--Elemento bold, italico e underline-->
<!ELEMENT bold (#PCDATA|italico)* >
<!ELEMENT italico (#PCDATA|bold)* >
<!ELEMENT underline (#PCDATA|bold)* >

=== jaimeleite/PRI/TP2/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "file:/C:/Users/ASUS/Desktop/PRI/TP2/pr.dtd">
<pr>
    <informacaoGeral>
        <dataInicio>2019-09-30</dataInicio>
        <dataFim>2019-09-30</dataFim>
        <nomeCadeira>PRI</nomeCadeira>
        <numTpc></numTpc>
        <professor>José Carlos Ramalho</professor>
        <titulo></titulo>
        <subTitulo>Com a descricao e numero do TPC</subTitulo>
    </informacaoGeral>
    <trabalhosAEntregar>
        
    </trabalhosAEntregar>
    <resumo>
        
    </resumo>
    <avaliandos>
        <aluno>
            <nome>Jaime Ricardo Faria Leite</nome>
            <curso>colocar um link para a página do curso</curso>
            <numeroAluno>A80757</numeroAluno>
            <email>a80757@alunos.uminho.pt</email>
        </aluno>
    </avaliandos>
</pr>
